export const GET_TASK_SUCCESS = 'GET_TASK_SUCCESS';
export const GET_TASK_PENDING = 'GET_TASK_PENDING';
export const GET_TASK_ERROR = 'GET_TASK_ERROR';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const DELETE_TASK_PENDING = 'DELETE_TASK_PENDING';
export const DELETE_TASK_ERROR = 'DELETE_TASK_ERROR';
