export const GET_TIMESHEETS_PENDING = 'GET_TIMESHEETS_PENDING';
export const GET_TIMESHEETS_SUCCESS = 'GET_TIMESHEETS_SUCCESS';
export const GET_TIMESHEETS_ERROR = 'GET_TIMESHEETS_ERROR';

export const DELETE_TIMESHEETS_PENDING = 'DELETE_TIMESHEETS_PENDING';
export const DELETE_TIMESHEETS_SUCCESS = 'DELETE_TIMESHEETS_SUCCESS';
export const DELETE_TIMESHEETS_ERROR = 'DELETE_TIMESHEETS_ERROR =';

export const POST_TIMESHEETS_PENDING = 'POST_TIMESHEETS_PENDING';
export const POST_TIMESHEETS_SUCCESS = 'POST_TIMESHEETS_SUCCESS';
export const POST_TIMESHEETS_ERROR = 'POST_TIMESHEETS_ERROR';

export const PUT_TIMESHEET_PENDING = 'PUT_TIMESHEET_PENDING';
export const PUT_TIMESHEET_SUCCESS = 'PUT_TIMESHEET_SUCCESS';
export const PUT_TIMESHEET_ERROR = 'PUT_TIMESHEET_ERROR';
