export const GET_ADMINS_PENDING = 'GET_ADMINS_PENDING';
export const GET_ADMINS_FULLFILLED = 'GET_ADMINS_FULLFILLED';
export const GET_ADMINS_ERROR = 'GET_ADMINS_ERROR';
export const DELETE_ADMINS_PENDING = 'DELETE_ADMINS_PENDING';
export const DELETE_ADMINS_FULLFILLED = 'DELETE_ADMINS_FULLFILLED';
export const DELETE_ADMINS_ERROR = 'DELETE_ADMINS_ERROR';

export const POST_ADMINS_PENDING = 'POST_ADMINS_PENDING';
export const POST_ADMINS_FULLFILLED = 'POST_ADMINS_FULLFILLED';
export const POST_ADMINS_ERROR = 'POST_ADMINS_ERROR';
export const PUT_ADMINS_PENDING = 'PUT_ADMINS_PENDING';
export const PUT_ADMINS_FULLFILLED = 'PUT_ADMINS_FULLFILLED';
export const PUT_ADMINS_ERROR = 'PUT_ADMINS_ERROR';
