export const GET_ADMINS_PENDING = 'GET_ADMINS_PENDING';
export const GET_ADMINS_FULLFILLED = 'GET_ADMINS_FULLFILLED';
export const GET_ADMINS_ERROR = 'GET_ADMINS_ERROR';
export const DELETE_ADMINS_PENDING = 'DELETE_ADMINS_PENDING';
export const DELETE_ADMINS_FULLFILLED = 'DELETE_ADMINS_FULLFILLED';
export const DELETE_ADMINS_ERROR = 'DELETE_ADMINS_ERROR';
